# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Summoney' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  # Pods for Summoney
    pod 'PKHUD', '~> 4.2' #4.2.0
    pod 'SnapKit'
    pod "MagicalRecord"
  target 'SummoneyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SummoneyUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
